<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Integration.Framework.Domain.Shared\Integration.Framework.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
